#!/bin/bash
title "Installing oci8..."

#check for # wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basic-linuxx64.zip
#wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip -- only libociicus.so
# wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-sqlplus-linuxx64.zip
# wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-tools-linuxx64.zip
# wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-sdk-linuxx64.zip
#unzip

mkdir /opt/oracle/
mv ~/Downloads/instantclient/ /opt/oracle/

sh -c "echo /opt/oracle/instantclient > /etc/ld.so.conf.d/oracle-instantclient.conf"
ldconfig

apt_install php-dev php-pear build-essential libaio1 default-jdk
pecl channel-update pecl.php.net
pecl install oci8
#sh -c "echo '; priority=10' > /etc/php/7.4/mods-available/oci8.ini"
sh -c "echo 'extension=oci8.so' >> /etc/php/7.4/mods-available/oci8.ini"
chmod 644 /etc/php/7.4/mods-available/oci8.ini
phpenmod oci8
php -i | grep oci8

